#pragma once
#include "ComponentType.h"
#include <QString>

enum COM_CATEGORY {
	COM_CATEGORY_MOVE = 0,
	COM_CATEGORY_FUNCTION = 1,
	COM_CATEGORY_LED = 2,
	COM_CATEGORY_OPERATION = 3,
	COM_CATEGORY_VARIBALE = 4,
	COM_CATEGORY_CYCLE = 5,
	COM_CATEGORY_SENSOR = 6,
	COM_CATEGORY_END = 7
};

const int COM_CATEGORY_TO_COM_TYPE[7][10] = { 
	{COM_TYPE_FORWARD, COM_TYPE_BACKWARD, COM_TYPE_LEFT, COM_TYPE_RIGHT, COM_TYPE_FORWARD_DISTENCE, COM_TYPE_BACKWARD_DISTENCE, COM_TYPE_LEFT_ANGLE, COM_TYPE_RIGHT_ANGLE},//COM_CATEGORY_MOVE
	{COM_TYPE_BEEP, COM_TYPE_DELAY},//COM_CATEGORY_FUNCTION
	{COM_TYPE_LIGHT, COM_TYPE_LIGHT2, COM_TYPE_LED1, COM_TYPE_LED2, COM_TYPE_LED3, COM_TYPE_LED4, COM_TYPE_LED5},//COM_CATEGORY_LED
	{},//COM_CATEGORY_OPERATION
	{},//COM_CATEGORY_VARIBALE
	{COM_TYPE_CYCLE_HEAD, COM_TYPE_COLLISION_CYCLE_HEAD},//COM_CATEGORY_CRYLE
	{COM_TYPE_INFRARED_HEAD, COM_TYPE_INFRARED_BRANCH_HEAD, COM_TYPE_COLLISION_DETECTION_HEAD, COM_TYPE_ALTITUDE_HEAD, COM_TYPE_TEMPERATURE_HEAD},//COM_CATEGORY_SENSOR
};