#pragma once

enum COM_TYPE {
	COM_TYPE_END = 0,

	COM_TYPE_FORWARD = 1,
	COM_TYPE_BACKWARD = 2,
	COM_TYPE_LEFT = 3,
	COM_TYPE_RIGHT = 4,
	COM_TYPE_FORWARD_DISTENCE = 5,
	COM_TYPE_BACKWARD_DISTENCE = 6,
	COM_TYPE_LEFT_ANGLE = 7,
	COM_TYPE_RIGHT_ANGLE = 8,

	COM_TYPE_BEEP = 9,
	COM_TYPE_DELAY = 11,

	COM_TYPE_LIGHT = 12,//≈‹¬Ìµ∆
	COM_TYPE_LIGHT2 = 13,//≈‹¬Ìµ∆2
	COM_TYPE_LED1 = 21,
	COM_TYPE_LED2 = 22,
	COM_TYPE_LED3 = 23,
	COM_TYPE_LED4 = 24,
	COM_TYPE_LED5 = 25,

	COM_TYPE_CYCLE_HEAD = 101,
	COM_TYPE_CYCLE_TAIL = 102,
	COM_TYPE_INFRARED_HEAD = 103,
	COM_TYPE_INFRARED_TAIL = 104,
	COM_TYPE_INFRARED_BRANCH_HEAD = 105,
	COM_TYPE_INFRARED_BRANCH_TAIL = 106,

	COM_TYPE_COLLISION_DETECTION_HEAD = 107,
	COM_TYPE_COLLISION_DETECTION_TAIL = 108,

	COM_TYPE_ALTITUDE_HEAD = 109,
	COM_TYPE_ALTITUDE_TAIL = 110,

	COM_TYPE_COLLISION_CYCLE_HEAD = 111,
	COM_TYPE_COLLISION_CYCLE_TAIL = 112,

	COM_TYPE_TEMPERATURE_HEAD = 113,
	COM_TYPE_TEMPERATURE_TAIL = 114,
};
